version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-setu-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_URL=sqlite:///./project_setu.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - WHO_CLIENT_ID=${WHO_CLIENT_ID:-}
      - WHO_CLIENT_SECRET=${WHO_CLIENT_SECRET:-}
      - ABHA_API_URL=${ABHA_API_URL:-https://dev.abdm.gov.in}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - backend_db:/app/project_setu
    networks:
      - setu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: project-setu-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - setu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional for production)
  nginx:
    image: nginx:alpine
    container_name: project-setu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - setu-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  backend_db:
    driver: local

networks:
  setu-network:
    driver: bridge
